### ISSUE TITLE
Issue with Version 9.2.4 on Node.js 18

### ISSUE THREAD

**Issue by rubengees** [achrinza/node-ipc#36]
Hi!

When installing the `v9` branch of this package (currently version `9.2.4`) on Node.js >= 18 with yarn I get the following error:

```
error @achrinza/node-ipc@9.2.4: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 | 18". Got "18.1.0"
error Found incompatible module.
```

I think that is because of a typo in the `package.json` where it needs to be `||` instead of `|`:

https://github.com/achrinza/node-ipc/blob/07c72fdf8f45ba7f93874cf8bd49c17d500ed87e/package.json#L10

**Comment by achrinza** [comment]
Thanks for raising this issue, @rubengees. I'll work to cut a release in the next 24 hours.

**Comment by rubengees** [comment]
Great, thanks for the quick answer and fix!

**Comment by rechun** [comment]
> Great, thanks for the quick answer and fix!

pleace ....i meet this bug  in my project..really need this
