### ISSUE TITLE
Support Node.js v19

### ISSUE THREAD

**Issue by jokay** [achrinza/node-ipc#40]
It seems Node.js v19 is not yet supported?

```sh
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @achrinza/node-ipc@9.2.5: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18". Got "19.0.0"
error Found incompatible module.
```

**Comment by achrinza** [comment]
Thanks for raising the issue! Support has been added to the necessary packages:

- `@achrinza/event-pubsub@5.0.8`
    - https://www.npmjs.com/package/@achrinza/event-pubsub/v/5.0.8
    - https://github.com/achrinza/event-pubsub/releases/tag/v5.0.8
- `@achrinza/node-ipc@10.1.7`
    - https://www.npmjs.com/package/@achrinza/node-ipc/v/10.1.7
    - https://github.com/achrinza/node-ipc/releases/tag/v10.1.7
- `@achrinza/node-ipc@9.2.6`
    - https://www.npmjs.com/package/@achrinza/node-ipc/v/9.2.6
    - https://github.com/achrinza/node-ipc/releases/tag/v9.2.6
- `@achrinza/strong-type@1.1.4`
    - https://www.npmjs.com/package/@achrinza/strong-type/v/1.1.4
    - https://github.com/achrinza/strong-type/releases/tag/v1.1.4
- `@achrinza/strong-type@0.1.10`
    - https://www.npmjs.com/package/@achrinza/strong-type/v/0.1.10
    - https://github.com/achrinza/strong-type/releases/tag/v0.1.10
- `@node-ipc/vanilla-test@1.4.12`
    - https://www.npmjs.com/package/@node-ipc/vanilla-test/v/1.4.12
    - https://github.com/node-ipc/vanilla-test/releases/tag/v1.4.12

**Comment by jokay** [comment]
Thx a lot :muscle:
