### ISSUE TITLE
Support Node.js v20

### ISSUE THREAD

**Issue by jokay** [achrinza/node-ipc#45]
It seems Node.js v20 is not yet supported?

```sh
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @achrinza/node-ipc@9.2.6: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18 || 19". Got "20.0.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by BingeCode** [comment]
Same problem here. Have you found a workaround?

EDIT: You can use the [`n` package](https://www.npmjs.com/package/n) to interactively change your node version.

**Comment by jokay** [comment]
Well for now, the only workaround is not to merge the dependency of the updated Node.js.

It affects sadly multiple projects / repositories on our side.

**Comment by JulienItard** [comment]
I need it too !

**Comment by achrinza** [comment]
Hi all, apologies Ive been away from GitHub fie a bit. Will make some time to settle this this week.
