### ISSUE TITLE
Node 22.0.0 : error @achrinza/node-ipc@9.2.8: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by jokay** [achrinza/node-ipc#61]
Can we get this working for Node **22.0.0**.

```sh
error @achrinza/node-ipc@9.2.8: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18 || 19 || 20 || 21". Got "22.0.0"
```

**Comment by achrinza** [comment]
Will get this up in the next 2 days

**Comment by ghost** [comment]
How's this going?

**Comment by sz4rlej** [comment]
Any info?

**Comment by achrinza** [comment]
Hi all, apologies for the delay.

[@achrinza/node-ipc@9.2.9](https://www.npmjs.com/package/@achrinza/node-ipc/v/9.2.9) has been published, which should have resolved the issue for majority of users.

@achrinza/node-ipc@10.x will be published shortly as well, pending version bumps to its dependencies.

**Comment by achrinza** [comment]
Explicit Node.js v22 support has been added to the necessary packages:

- `@achrinza/event-pubsub@5.0.11`
    - https://www.npmjs.com/package/@achrinza/event-pubsub/v/5.0.11
    - https://github.com/achrinza/event-pubsub/releases/tag/v5.0.11
- `@achrinza/node-ipc@10.1.11`
    - https://www.npmjs.com/package/@achrinza/node-ipc/v/10.1.11
    - https://github.com/achrinza/node-ipc/releases/tag/v10.1.11
- `@achrinza/node-ipc@9.2.9`
    - https://www.npmjs.com/package/@achrinza/node-ipc/v/9.2.9
    - https://github.com/achrinza/node-ipc/releases/tag/v9.2.9
- `@achrinza/strong-type@1.1.20`
    - https://www.npmjs.com/package/@achrinza/strong-type/v/1.1.20
    - https://github.com/achrinza/strong-type/releases/tag/v1.1.20
- `@achrinza/strong-type@0.1.14`
    - https://www.npmjs.com/package/@achrinza/strong-type/v/0.1.14
    - https://github.com/achrinza/strong-type/releases/tag/v0.1.14
- `@node-ipc/vanilla-test@1.4.15`
    - https://www.npmjs.com/package/@node-ipc/vanilla-test/v/1.4.15
    - https://github.com/node-ipc/vanilla-test/releases/tag/v1.4.15
