### ISSUE TITLE
@achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "20.12.1"

### ISSUE THREAD

**Issue by ZTkt** [achrinza/node-ipc#63]

**Comment by achrinza** [comment]
Please upgrade to `@achrinza/node-ipc@9.2.7`.

see: https://github.com/achrinza/node-ipc/issues/61
see: https://github.com/achrinza/node-ipc/commit/e033f4399fa3551b537aed2c1472f70f323d1feb
